### ISSUE TITLE
Link errors

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/shelf-pack-cpp#10]
```
duplicate symbol __ZN6mapboxlsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_3BinE in:
    /Users/john/Development/mapbox-gl-native/build/macos/mbgl.build/Debug/mbgl-test.build/Objects-normal/x86_64/bucket.test.o
    /Users/john/Development/mapbox-gl-native/build/macos/Debug/libmbgl-core.a(render_symbol_layer.o)
```

That demangles to `mapbox::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, mapbox::Bin const&)`, which is [defined](https://github.com/mapbox/shelf-pack-cpp/blob/711acc1da78c488071f823aa3791d7fd189058e4/include/shelf-pack.hpp#L80) without the `inline` keyword, so it ends up duplicated in any translation unit that includes shelf-pack.hpp.

Can we remove this function or move it to test.cpp so there's no `<iostream>` dependency in the header?

**Comment by bhousel** [comment]
closed in 5a3599f
